spring:
  main:
    web-application-type: servlet
  application:
    name: demo
  cloud:
    config:
      enabled: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://yourtenant.com/

graphql:
  servlet:
    actuator-metrics: true
    websocket:
      enabled: false
    exception-handlers-enabled: true

management:
  server:
    port: 9321
  endpoints:
    web:
      base-path: '/metrics'
      exposure:
        include: "info, health, prometheus"
  endpoint:
    health:
      enabled: true
      probes:
        enabled: true
      show-details: always
  prometheus:
    metrics:
      export:
        enabled: true

server:
  port: 8081
